AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/MultilineIfModifier:
  Enabled: false
